---
title: 'Error Handling'
description: '期待されたエラーを表示し、キャッチされない例外を処理する方法を学びましょう。'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは2つのカテゴリに分けられます: **期待されたエラー**と**キャッチされない例外**です：

- **期待されたエラーを返り値としてモデル化する**: Server Actionsで期待されたエラーに対して`try`/`catch`を使用するのを避けましょう。これらのエラーを管理し、クライアントに返すために`useFormState`を使用してください。
- **予期しないエラーにはエラーバウンダリーを使用する**: `error.tsx`と`global-error.tsx`ファイルを使用してエラーバウンダリーを実装し、予期しないエラーを処理し、フォールバックUIを提供しましょう。

## 期待されたエラーの処理 {#handling-expected-errors}

期待されたエラーとは、アプリケーションの通常の動作中に発生する可能性のあるもので、[サーバーサイドのフォームバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)や失敗したリクエストからのエラーなどです。これらのエラーは明示的に処理し、クライアントに返す必要があります。

### Server Actionsからの期待されたエラーの処理 {#handling-expected-errors-from-server-actions}

`useFormState`フックを使用して、エラー処理を含むServer Actionsの状態を管理します。このアプローチでは、期待されたエラーに対して`try`/`catch`ブロックを避け、例外としてスローするのではなく返り値としてモデル化するべきです。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

その後、`useFormState`フックにアクションを渡し、返された`state`を使用してエラーメッセージを表示できます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

> **Good to know**: これらの例は、Next.js App RouterにバンドルされているReactの`useFormState`フックを使用しています。React 19を使用している場合は、代わりに`useActionState`を使用してください。詳細については[Reactのドキュメント](https://react.dev/reference/react/useActionState)を参照してください。

返された状態を使用して、クライアントコンポーネントからトーストメッセージを表示することもできます。

### Server Componentsからの期待されたエラーの処理 {#handling-expected-errors-from-server-components}

Server Componentの内部でデータをフェッチする際には、レスポンスを使用してエラーメッセージを条件付きでレンダリングしたり、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)できます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## キャッチされない例外 {#uncaught-exceptions}

キャッチされない例外は、アプリケーションの通常のフローでは発生するべきでないバグや問題を示す予期しないエラーです。これらはエラーをスローすることで処理され、エラーバウンダリーによってキャッチされます。

- **Common:** root レイアウトの下でキャッチされないエラーを`error.js`で処理する
- **Optional:** ネストされた`error.js`ファイル（例: `app/dashboard/error.js`）を使用して細かいキャッチされないエラーを処理する
- **Uncommon:** root レイアウトでキャッチされないエラーを`global-error.js`で処理する

### エラーバウンダリーの使用 {#using-error-boundaries}

Next.jsは、キャッチされない例外を処理するためにエラーバウンダリーを使用します。エラーバウンダリーは、その子コンポーネントでエラーをキャッチし、クラッシュしたコンポーネントのtreeの代わりにフォールバックUIを表示します。

ルートセグメントに`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートすることでエラーバウンダリーを作成します：

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // エラーバウンダリーはClient Componentsでなければなりません

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラーレポートサービスに記録する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みる
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // エラーバウンダリーはClient Componentsでなければなりません

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラーレポートサービスに記録する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みる
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーを親エラーバウンダリーにバブルアップさせたい場合、`error`コンポーネントをレンダリングするときに`throw`することができます。

### ネストされたルートでのエラー処理 {#handling-errors-in-nested-routes}

エラーは最も近い親エラーバウンダリーにバブルアップします。これにより、[ルートの階層](/docs/app/building-your-application/routing#component-hierarchy)のさまざまなレベルに`error.tsx`ファイルを配置して細かいエラーハンドリングが可能になります。

<Image
  alt="ネストされたエラーコンポーネントの階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

あまり一般的ではありませんが、[国際化](/docs/app/building-your-application/routing/internationalization)を活用している場合でも、root レイアウトにある`app/global-error.js`を使用してエラーを処理できます。グローバルエラーUIでは、root レイアウトやテンプレートを置き換えるため、独自の`<html>`および`<body>`タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // エラーバウンダリーはClient Componentsでなければなりません

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorはhtmlおよびbodyタグを含める必要があります
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // エラーバウンダリーはClient Componentsでなければなりません

export default function GlobalError({ error, reset }) {
  return (
    // global-errorはhtmlおよびbodyタグを含める必要があります
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
