---
title: 'Error Handling'
description: '予期したエラーを表示し、未捕捉の例外を処理する方法を学ぶ。'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは、**予期したエラー**と**未捕捉の例外**の2つのカテゴリーに分けることができます：

- **予期したエラーを返り値としてモデリングする**：Server Actionsにおいて予期したエラーには`try`/`catch`を使用しないようにします。これらのエラーは`useFormState`を使用して管理し、クライアントに返すようにしてください。
- **予期しないエラーにはエラーバウンダリを使用する**：予期しないエラーを処理し、フォールバックUIを提供するために、`error.tsx`および`global-error.tsx`ファイルを使用してエラーバウンダリを実装します。

## 予期したエラーの処理 {#handling-expected-errors}

予期したエラーとは、アプリケーションの通常の操作中に発生する可能性があるエラーのことを指します。例えば、[サーバー側のフォームバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)や失敗したリクエストからのエラーです。これらのエラーは明示的に処理し、クライアントに返す必要があります。

### Server Actionsからの予期したエラーの処理 {#handling-expected-errors-from-server-actions}

`useFormState`フックを使用して、Server Actionsの状態を管理し、エラーを処理します。このアプローチでは、予期したエラーのために`try`/`catch`ブロックを使用せず、例外を投げるのではなく返り値としてモデリングすることを避けます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' } // 有効なメールアドレスを入力してください
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' } // 有効なメールアドレスを入力してください
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

その後、アクションを`useFormState`フックに渡し、返される`state`を使用してエラーメッセージを表示することができます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

> **Good to know**: これらの例では、Next.js App RouterにバンドルされているReactの`useFormState`フックを使用します。React 19を使用している場合は、`useActionState`を使用してください。詳細は[React のドキュメント](https://react.dev/reference/react/useActionState)を参照してください。

返された状態を使用して、クライアントコンポーネントからトーストメッセージを表示することもできます。

### Server Componentsからの予期したエラーの処理 {#handling-expected-errors-from-server-components}

Server Component内でデータをフェッチする際には、レスポンスを使用して条件付きでエラーメッセージをレンダリングしたり、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)を使用したりできます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.' // エラーが発生しました。
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.' // エラーが発生しました。
  }

  return '...'
}
```

</TabItem>
</Tabs>

## 未捕捉の例外 {#uncaught-exceptions}

未捕捉の例外は、アプリケーションの通常のフローでは発生すべきではないバグまたは問題を示す予期しないエラーです。これらはエラーをスローすることで処理され、その後、エラーバウンダリによって捕捉されます。

- **Common:** `root レイアウト`の下で未捕捉のエラーを`error.js`で処理します。
- **Optional:** ネストされた`error.js`ファイル（例：`app/dashboard/error.js`）を使用して、細かい未捕捉のエラーを処理します。
- **Uncommon:** `root レイアウト`内で未捕捉のエラーを`global-error.js`で処理します。

### エラーバウンダリの使用 {#using-error-boundaries}

Next.jsでは、エラーバウンダリを使用して未捕捉の例外を処理します。エラーバウンダリは、子コンポーネント内のエラーを捕捉し、クラッシュしたコンポーネントツリーの代わりにフォールバックUIを表示します。

エラーバウンダリを作成するには、ルートセグメント内に`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートします：

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // エラーバウンダリはClient Componentsである必要があります

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラーレポートサービスに記録する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいっていません！</h2>
      <button
        onClick={
          // セグメントを再レンダリングすることにより回復を試みる
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // エラーバウンダリはClient Componentsである必要があります

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラーレポートサービスに記録する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいっていません！</h2>
      <button
        onClick={
          // セグメントを再レンダリングすることにより回復を試みる
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーを親のエラーバウンダリまでバブルアップさせたい場合は、`error`コンポーネントをレンダリングする際にスローすることができます。

### ネストされたルートでのエラー処理 {#handling-errors-in-nested-routes}

エラーは最も近い親のエラーバウンダリにバブルアップします。これは、[ルート階層](/docs/app/building-your-application/routing#component-hierarchy)のさまざまなレベルに`error.tsx`ファイルを配置することで、細かいエラー処理を可能にします。

<Image
  alt="ネストされたエラコンポーネントの階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

あまり一般的ではありませんが、[国際化](/docs/app/building-your-application/routing/internationalization)を活用する場合でも、`root レイアウト`を使用して`root app`ディレクトリに位置する`app/global-error.js`を使ってエラーを処理することができます。グローバルエラーUIは、アクティブなときに`root レイアウト`やテンプレートを置換するために、`<html>`と`<body>`タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // エラーバウンダリはClient Componentsである必要があります

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>何かがうまくいっていません！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // エラーバウンダリはClient Componentsである必要があります

export default function GlobalError({ error, reset }) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>何かがうまくいっていません！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
