---
title: 'エラー処理'
description: '予期されたエラーを表示し、未捕捉の例外を処理する方法を学びます'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは次の2つのカテゴリーに分けられます：**予期されたエラー**と**未捕捉の例外**：

- **予期されたエラーを戻り値としてモデル化する**：Server Actionsで予期されたエラーには`try`/`catch`を避けましょう。`useFormState`を使ってこれらのエラーを管理し、クライアントに返します
- **予期しないエラーにはエラーバウンダリを使用する**：`error.tsx`と`global-error.tsx`ファイルを使用してエラーバウンダリを実装し、予期しないエラーを処理し、フォールバックUIを提供します

## 予期されたエラーの処理 {#handling-expected-errors}

予期されたエラーとは、アプリケーションの通常の動作中に発生する可能性のあるエラーのことです。例えば、[サーバーサイドのフォームバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)や失敗したリクエストが含まれます。これらのエラーは明示的に処理し、クライアントに返す必要があります。

### Server Actionsから予期されたエラーを処理する {#handling-expected-errors-from-server-actions}

`useFormState`フックを使用してServer Actionsの状態を管理し、エラーを処理します。この方法は、予期されたエラーを例外として投げずに戻り値としてモデル化することであり、`try`/`catch`ブロックを回避します。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

// ユーザーを作成する関数
export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    // メールアドレスが有効か確認してください
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

// ユーザーを作成する関数
export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    // メールアドレスが有効か確認してください
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

その後、アクションを`useFormState`フックに渡し、返された`state`を使用してエラーメッセージを表示することができます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

> **Good to know**: これらの例は、Next.jsのApp Routerに付属のReactの`useFormState`フックを使用しています。React 19を使用している場合は、代わりに`useActionState`を利用してください。詳細は[Reactのドキュメント](https://react.dev/reference/react/useActionState)を参照してください。

クライアントコンポーネントからトーストメッセージを表示するために返された状態を使用することもできます。

### サーバーコンポーネントから予期されたエラーを処理する {#handling-expected-errors-from-server-components}

Server Componentの内部でデータをフェッチする場合、レスポンスを使用してエラーメッセージを条件付きでレンダリングするか、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)を行います。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## 未捕捉の例外 {#uncaught-exceptions}

未捕捉の例外は、アプリケーションの通常のフロー中に発生してはならないバグや問題を示す予期しないエラーです。これらはエラーとして投げて、エラーバウンダリによって捕捉されるべきです。

- **共通のケース**：root レイアウト下で未捕捉エラーを処理するには`error.js`を使用
- **オプションのケース**：ネストされた`error.js`ファイル（例：`app/dashboard/error.js`）を使用して詳細な未捕捉エラーを処理
- **まれなケース**：root レイアウトで未捕捉エラーを処理するには`global-error.js`を使用

### エラーバウンダリの使用 {#using-error-boundaries}

Next.jsはエラーバウンダリを使用して未捕捉の例外を処理します。エラーバウンダリはその子コンポーネントで発生したエラーを捕捉し、クラッシュしたコンポーネントツリーの代わりにフォールバックUIを表示します。

ルートセグメント内に`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートすることでエラーバウンダリを作成します。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // エラーバウンダリはクライアントコンポーネントである必要があります

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラーレポートサービスにログとして記録
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // セグメントを再レンダリングしようと試みて回復を試みる
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // エラーバウンダリはクライアントコンポーネントである必要があります

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラーレポートサービスにログとして記録
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // セグメントを再レンダリングしようと試みて回復を試みる
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーを親のエラーバウンダリにバブルアップさせたい場合は、`error`コンポーネントをレンダリングする際に`throw`することができます。

### ネストされたルートでのエラー処理 {#handling-errors-in-nested-routes}

エラーは最も近い親のエラーバウンダリにバブルアップします。これにより、[ルート階層](/docs/app/building-your-application/routing#component-hierarchy)の異なるレベルに`error.tsx`ファイルを配置することで、詳細なエラー処理が可能になります。

<Image
  alt="ネストされたエラーコンポーネント階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

まれですが、[国際化](/docs/app/building-your-application/routing/internationalization)を活用する場合でも、root レイアウトを使用してエラーを処理することができます。グローバルエラーUIは独自の`<html>`タグと`<body>`タグを定義する必要があります。これは有効時にroot レイアウトやテンプレートを置き換えるためです。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // エラーバウンダリはクライアントコンポーネントである必要があります

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // エラーバウンダリはクライアントコンポーネントである必要があります

export default function GlobalError({ error, reset }) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
