---
title: 'エラー処理'
description: '予期されるエラーの表示方法とキャッチされない例外の処理方法を学びます'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは2つのカテゴリーに分けることができます: **予期されるエラー** と **キャッチされない例外**;

- **予期されるエラーを戻り値としてモデル化する**: Server Actions では予期されるエラーに `try` / `catch` を使用するのを避けます。これらのエラーを管理し、クライアントに返すために `useFormState` を使用します
- **予期しないエラーにはエラーバウンダリを使用する**: `error.tsx` と `global-error.tsx` ファイルを使用してエラーバウンダリを実装し、予期しないエラーを処理しフォールバックUIを提供します

## 予期されるエラーの処理 {#handling-expected-errors}

予期されるエラーとは、[サーバーサイドのフォームバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation) や失敗したリクエストなど、アプリケーションの通常の動作中に発生する可能性のあるエラーのことです。これらのエラーは明示的に処理され、クライアントに返されるべきです。

### Server Actions からの予期されるエラーの処理 {#handling-expected-errors-from-server-actions}

`useFormState` フックを使用して、Server Actions の状態を管理し、エラーを処理します。このアプローチでは、予期されるエラーに対して `try` / `catch` ブロックを避け、エラーを例外としてスローするのではなく戻り値としてモデル化することが推奨されます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '正しいメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '正しいメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

次に、アクションを `useFormState` フックに渡し、返された `state` を使用してエラーメッセージを表示できます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

> **Good to know**: これらの例は Next.js App Router にバンドルされた React の `useFormState` フックを使用しています。React 19 を使用している場合は、代わりに `useActionState` を使用してください。詳細は [React のドキュメント](https://react.dev/reference/react/useActionState) を参照してください。

返された状態を使用してクライアントコンポーネントからトーストメッセージを表示することもできます。

### Server components からの予期されるエラーの処理 {#handling-expected-errors-from-server-components}

Server Component 内でデータを取得するとき、レスポンスを使用してエラーメッセージを条件付きでレンダリングするか、[リダイレクト](/docs/app/building-your-application/routing/redirecting#redirect-function) することができます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## キャッチされない例外 {#uncaught-exceptions}

キャッチされない例外とは、アプリケーションの通常のフロー中に発生してはいけないバグや問題を示す予期しないエラーです。これらはエラーをスローすることで処理され、エラーバウンダリによってキャッチされます。

- **一般的**: `error.js` を使用して root レイアウト以下のキャッチされないエラーを処理します
- **オプショナル**: ネストされた `error.js` ファイルを使用して詳細なキャッチされないエラーを処理します (例: `app/dashboard/error.js`)
- **稀**: `global-error.js` を使用して root レイアウト内のキャッチされないエラーを処理します

### エラーバウンダリの使用 {#using-error-boundaries}

Next.js はエラーバウンダリを使用してキャッチされない例外を処理します。エラーバウンダリは、子コンポーネントのエラーをキャッチし、クラッシュしたコンポーネントツリーの代わりにフォールバック UI を表示します。

ルートセグメント内に `error.tsx` ファイルを追加し、React コンポーネントをエクスポートすることでエラーバウンダリを作成します:

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // エラーバウンダリはクライアントコンポーネントでなければなりません

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラーレポートサービスにログする
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいっていません！</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みる
          () => reset()
        }
      >
        再試行
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // エラーバウンダリはクライアントコンポーネントでなければなりません

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラーレポートサービスにログする
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいっていません！</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みる
          () => reset()
        }
      >
        再試行
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーを親のエラーバウンダリにバブルアップさせたい場合は、`error` コンポーネントをレンダリングするときに `throw` できます。

### ネストされたルートでのエラー処理 {#handling-errors-in-nested-routes}

エラーは最も近い親のエラーバウンダリにバブルアップします。これにより、[ルート階層](/docs/app/building-your-application/routing#component-hierarchy) の異なるレベルに `error.tsx` ファイルを配置することで、詳細なエラー処理が可能になります。

<Image
  alt="ネストされたエラーコンポーネントの階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

あまり一般的ではありませんが、[国際化](/docs/app/building-your-application/routing/internationalization) を活用している場合でも、root のアプリディレクトリにある `app/global-error.js` を使用して root レイアウトでエラーを処理することができます。グローバルエラー UI は、それがアクティブなときに root レイアウトまたはテンプレートを置き換えるため、独自の `<html>` と `<body>` タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // エラーバウンダリはクライアントコンポーネントでなければなりません

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-error は html と body タグを含む必要があります
    <html>
      <body>
        <h2>何かがうまくいっていません！</h2>
        <button onClick={() => reset()}>再試行</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // エラーバウンダリはクライアントコンポーネントでなければなりません

export default function GlobalError({ error, reset }) {
  return (
    // global-error は html と body タグを含む必要があります
    <html>
      <body>
        <h2>何かがうまくいっていません！</h2>
        <button onClick={() => reset()}>再試行</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
