---
title: 'エラーハンドリング'
description: '予期されたエラーを表示し、捕捉されない例外を処理する方法を学びましょう。'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは、**予期されたエラー**と**捕捉されない例外**の2つのカテゴリに分けられます：

- **予期されたエラーを戻り値としてモデル化する**：Server Actionsでは予期されたエラーに`try`/`catch`を使用するのは避けましょう。`useFormState`を使用してこれらのエラーを管理し、クライアントに返却します
- **予期しないエラーにはエラーバウンダリーを使用する**：`error.tsx`および`global-error.tsx`ファイルを使用してエラーバウンダリーを実装し、予期しないエラーを処理し、フォールバックUIを提供します

## 予期されたエラーの処理 {#handling-expected-errors}

予期されたエラーは、アプリケーションの通常の操作中に発生する可能性のあるエラーです。たとえば、[サーバ側フォームバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)からのエラーや失敗したリクエストなどです。これらのエラーは明示的に処理され、クライアントに返される必要があります。

### サーバアクションからの予期されたエラーの処理 {#handling-expected-errors-from-server-actions}

`useFormState`フックを使用して、Server Actionsの状態を管理し、エラーの処理を行います。このアプローチでは、`try`/`catch`ブロックを避け、予期されたエラーは例外としてスローするのではなく戻り値としてモデル化されるべきです。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

// ユーザーを作成する非同期関数
export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

// ユーザーを作成する非同期関数
export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

次に、アクションを`useFormState`フックに渡し、返された`state`を使用してエラーメッセージを表示できます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

> **Good to know**: これらの例はReactの`useFormState`フックを使用しています。このフックはNext.js App Routerにバンドルされています。React 19を使用している場合は、代わりに`useActionState`を使用してください。詳細は[Reactのドキュメント](https://react.dev/reference/react/useActionState)を参照してください。

また、返されたstateを使用してクライアントコンポーネントからトーストメッセージを表示することもできます。

### サーバコンポーネントからの予期されたエラーの処理 {#handling-expected-errors-from-server-components}

Server Componentの内部でデータを取得する際に、レスポンスを利用してエラーメッセージを条件付きでレンダリングしたり、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)を行ったりできます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
// ページのデフォルトエクスポート
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
// ページのデフォルトエクスポート
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## 捕捉されない例外 {#uncaught-exceptions}

捕捉されない例外は、アプリケーションの通常のフローで発生すべきではないバグや問題を示す予期しないエラーです。これらはエラーをスローすることで処理され、その後エラーバウンダリーによって捕捉されます。

- **一般的：** root レイアウトの下で`error.js`を使用して捕捉されないエラーを処理する
- **オプション：** ネストされた`error.js`ファイル（例：`app/dashboard/error.js`）を使用して詳細な捕捉されないエラーを処理する
- **稀：** root レイアウトで`global-error.js`を使用して捕捉されないエラーを処理する

### エラーバウンダリーの使用 {#using-error-boundaries}

Next.jsは捕捉されない例外を処理するためにエラーバウンダリーを使用します。エラーバウンダリーは子コンポーネント内のエラーをキャッチし、クラッシュしたコンポーネントツリーの代わりにフォールバックUIを表示します。

ルートセグメント内に`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートすることでエラーバウンダリーを作成します：

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // エラーバウンダリーはクライアントコンポーネントである必要があります

import { useEffect } from 'react'

// デフォルトエクスポートのエラーファンクション
export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラー報告サービスにログ送信する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何か問題が発生しました！</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みる
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // エラーバウンダリーはクライアントコンポーネントである必要があります

import { useEffect } from 'react'

// デフォルトエクスポートのエラーファンクション
export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラー報告サービスにログ送信する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何か問題が発生しました！</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みる
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーが親エラーバウンダリーにバブルアップすることを望む場合、`error`コンポーネントをレンダリングする際に`throw`できます。

### ネストされたルートでのエラー処理 {#handling-errors-in-nested-routes}

エラーは最も近い親エラーバウンダリーまでバブルアップします。これにより、[ルート階層](/docs/app/building-your-application/routing#component-hierarchy)のさまざまなレベルで`error.tsx`ファイルを配置することで詳細なエラーハンドリングが可能になります。

<Image
  alt="ネストされたエラーコンポーネント階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

あまり一般的ではありませんが、国際化を利用する場合でも、root アプリディレクトリにある`app/global-error.js`を使用してroot レイアウトでエラーを処理できます。グローバルエラーUIは、アクティブな際にroot レイアウトまたはテンプレートを置き換えるため、独自の`<html>`および`<body>`タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // エラーバウンダリーはクライアントコンポーネントである必要があります

// グローバルエラーファンクションのデフォルトエクスポート
export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorにはhtmlおよびbodyタグを含める必要があります
    <html>
      <body>
        <h2>何か問題が発生しました！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // エラーバウンダリーはクライアントコンポーネントである必要があります

// グローバルエラーファンクションのデフォルトエクスポート
export default function GlobalError({ error, reset }) {
  return (
    // global-errorにはhtmlおよびbodyタグを含める必要があります
    <html>
      <body>
        <h2>何か問題が発生しました！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
