---
title: 'エラーハンドリング'
description: '予期されるエラーを表示し、未捕捉の例外を処理する方法を学びましょう。'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは2つのカテゴリーに分けることができます： **予期されるエラー**と**未捕捉の例外**:

- **予期されるエラーを返り値としてモデル化する**: Server Actionsで予期されるエラーに対して`try`/`catch`を使用することを避けます。これらのエラーを管理し、クライアントに返すために`useFormState`を使用します。
- **予期しないエラーはerror boundaryを使用する**: `error.tsx`と`global-error.tsx`ファイルを使用してerror boundaryを実装し、予期しないエラーを処理し、フォールバックのUIを提供します。

## 予期されるエラーの処理 {#handling-expected-errors}

予期されるエラーとは、アプリケーションの通常の動作中に発生する可能性があるもので、[サーバーサイドのフォームバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)や失敗したリクエストからのものなどです。これらのエラーは明示的に処理し、クライアントに返されるべきです。

### Server Actionsからの予期されるエラーの処理 {#handling-expected-errors-from-server-actions}

`useFormState`フックを使用して、Server Actionsの状態を管理し、エラーを処理します。このアプローチは、予期されるエラーに対して`try`/`catch`ブロックを避け、例外として投げるのではなく、返り値としてモデル化するべきです。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

その後、アクションを`useFormState`フックに渡し、返された`state`を使用してエラーメッセージを表示できます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

> **Good to know**: これらの例はReactの`useFormState`フックを使用しており、Next.jsのApp Routerと一緒にバンドルされています。React 19を使用している場合は、代わりに`useActionState`を使用してください。詳細は[Reactドキュメント](https://react.dev/reference/react/useActionState)を参照してください。

また、返された状態を使用してクライアントコンポーネントからトーストメッセージを表示することもできます。

### Server Componentsからの予期されるエラーの処理 {#handling-expected-errors-from-server-components}

Server Component内部でデータを取得する際、レスポンスを使用してエラーメッセージを条件付きでレンダリングしたり、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)を使用することができます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## 未捕捉の例外 {#uncaught-exceptions}

未捕捉の例外は、バグや通常のアプリケーションの流れでは発生しないはずの問題を示す予期しないエラーです。これらはエラーをスローすることで処理され、その後、error boundaryによってキャッチされます。

- **一般的:** `error.js`を使用してroot レイアウト以下の未捕捉のエラーを処理します。
- **任意:** ネストされた`error.js`ファイル（例：`app/dashboard/error.js`）を使用して詳細な未捕捉のエラーを処理します。
- **稀:** root レイアウトで未捕捉のエラーを処理するために`global-error.js`を使用します。

### Error Boundaryの使用 {#using-error-boundaries}

Next.jsは、未捕捉の例外を処理するためにerror boundaryを使用します。Error boundaryは子コンポーネント内のエラーをキャッチし、クラッシュしたコンポーネントのtreeの代わりにフォールバックUIを表示します。

ルートセグメント内に`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートすることでerror boundaryを作成します:

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // Error boundaryはClient Componentsでなければなりません

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラーレポートサービスにログします
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいきませんでした！</h2>
      <button
        onClick={
          // セグメントを再レンダリングして回復を試みます
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // Error boundaryはClient Componentsでなければなりません

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラーレポートサービスにログします
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいきませんでした！</h2>
      <button
        onClick={
          // セグメントを再レンダリングして回復を試みます
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーを親のerror boundaryに伝播させたい場合は、`error`コンポーネントをレンダリングする際に`throw`することができます。

### ネストされたルートでのエラー処理 {#handling-errors-in-nested-routes}

エラーは最も近い親のerror boundaryに伝播します。これにより、[ルート階層](/docs/app/building-your-application/routing#component-hierarchy)の異なるレベルに`error.tsx`ファイルを配置することで詳細なエラーハンドリングが可能になります。

<Image
  alt="ネストされたエラーコンポーネント階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

あまり一般的ではありませんが、[国際化](/docs/app/building-your-application/routing/internationalization)を活用している場合でも、rootアプリディレクトリにある`app/global-error.js`を使用してroot レイアウト内のエラーを処理できます。グローバルエラーUIは自身の`<html>`タグと`<body>`タグを定義する必要があります。アクティブ時にはroot レイアウトまたはテンプレートの代わりになります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // Error boundaryはClient Componentsでなければなりません

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorはhtmlとbodyタグを含む必要があります
    <html>
      <body>
        <h2>何かがうまくいきませんでした！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // Error boundaryはClient Componentsでなければなりません

export default function GlobalError({ error, reset }) {
  return (
    // global-errorはhtmlとbodyタグを含む必要があります
    <html>
      <body>
        <h2>何かがうまくいきませんでした！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
