---
title: 'エラー処理'
description: '予想されるエラーを表示し、キャッチされていない例外を処理する方法について学びましょう。'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは2つのカテゴリに分けられます：**予想されるエラー** と **キャッチされていない例外**：

- **予想されるエラーは返り値としてモデル化する**：Server Actionsで予想されるエラーに`try`/`catch`を使うことを避けるようにします。これらのエラーを管理し、クライアントに返すために`useFormState`を使用してください。
- **予期しないエラーにはエラー境界を使用する**：予期しないエラーを処理し、フォールバックUIを提供するために、`error.tsx` と `global-error.tsx` ファイルを使用してエラー境界を実装します。

## 予想されるエラーの処理 {#handling-expected-errors}

予想されるエラーとは、アプリケーションが通常動作する中で発生する可能性があるもので、[サーバーサイドのフォーム検証](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)や失敗したリクエストからのエラーが含まれます。これらのエラーは明示的に処理し、クライアントに返す必要があります。

### Server Actionsからの予想されるエラーの処理 {#handling-expected-errors-from-server-actions}

Server Actionsの状態を管理し、エラーを処理するために`useFormState`フックを使用しましょう。このアプローチは、`try`/`catch`ブロックを予想されるエラーのために使わないようにし、返り値としてモデル化するべきものを例外としてスローしないようにします。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

次に、アクションを`useFormState`フックに渡し、返された`state`を使用してエラーメッセージを表示します。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

> **Good to know**: これらの例では、Next.jsのApp RouterにバンドルされているReactの`useFormState`フックを使用しています。React 19を使用している場合は、代わりに`useActionState`を使用してください。詳細は[Reactのドキュメント](https://react.dev/reference/react/useActionState)をご覧ください。

返された状態を使用して、クライアントコンポーネントからトーストメッセージを表示することもできます。

### Server Componentsからの予想されるエラーの処理 {#handling-expected-errors-from-server-components}

Server Component内部でデータを取得する際に、応答を使用してエラーメッセージを条件付きでレンダリングするか、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)することができます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## キャッチされていない例外 {#uncaught-exceptions}

キャッチされていない例外は、アプリケーションの通常の流れで発生すべきではないバグや問題を示す予期しないエラーです。これらはエラーを投げて処理されるべきであり、その後エラー境界によってキャッチされます。

- **共通**: `error.js`でroot レイアウト以下のキャッチされていないエラーを処理します。
- **オプション**: ネストされた`error.js`ファイル（例：`app/dashboard/error.js`）で細かなキャッチされていないエラーを処理します。
- **非共通**: `global-error.js`でroot レイアウト内のキャッチされていないエラーを処理します。

### エラー境界の使用 {#using-error-boundaries}

Next.jsはキャッチされていない例外を処理するためにエラー境界を使用します。エラー境界はその子コンポーネント内のエラーをキャッチし、クラッシュしたコンポーネントツリーの代わりにフォールバックUIを表示します。

ルートセグメント内に`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートすることでエラー境界を作成します。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // エラー境界はClient Componentsでなければなりません

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラーレポートサービスにログします
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいきませんでした！</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みます
          () => reset()
        }
      >
        もう一度試してください
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // エラー境界はClient Componentsでなければなりません

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラーレポートサービスにログします
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいきませんでした！</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みます
          () => reset()
        }
      >
        もう一度試してください
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

`error`コンポーネントをレンダリングするときに`throw`することで、エラーが親エラー境界にバブルアップするようにすることができます。

### ネストされたルートでのエラーの処理 {#handling-errors-in-nested-routes}

エラーは最も近い親エラー境界にバブルアップします。これにより、[ルート階層](/docs/app/building-your-application/routing#component-hierarchy)の異なるレベルに`error.tsx`ファイルを配置することで、細かいエラー処理が可能になります。

<Image
  alt="ネストされたエラーコンポーネント階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

あまり一般的ではありませんが、[国際化](/docs/app/building-your-application/routing/internationalization)を活用しながら、root レイアウトを使用してエラーを処理することもできます。グローバルエラーUIは`app/global-error.js`に定義され、ルートappディレクトリに配置されます。アクティブになるとroot レイアウトやテンプレートを置き換えるため、独自の`<html>`および`<body>`タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // エラー境界はClient Componentsでなければなりません

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorにはhtmlおよびbodyタグを含める必要があります
    <html>
      <body>
        <h2>何かがうまくいきませんでした！</h2>
        <button onClick={() => reset()}>もう一度試してください</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // エラー境界はClient Componentsでなければなりません

export default function GlobalError({ error, reset }) {
  return (
    // global-errorにはhtmlおよびbodyタグを含める必要があります
    <html>
      <body>
        <h2>何かがうまくいきませんでした！</h2>
        <button onClick={() => reset()}>もう一度試してください</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
