---
title: 'エラーハンドリング'
description: '予期されるエラーを表示し、キャッチされない例外を処理する方法を学びます。'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは**予期されるエラー**と**キャッチされない例外**の2つに分けることができます：

- **予期されるエラーは戻り値としてモデル化します**：Server Actionsで予期されるエラーに対しては`try`/`catch`を使用しないようにしましょう。`useFormState`を使用してこれらのエラーを管理し、クライアントに返します
- **予期しないエラーにはエラーボーダリーを使用します**：`error.tsx`と`global-error.tsx`ファイルを使用してエラーボーダリーを実装し、予期しないエラーを処理し、フォールバックUIを提供します

## 予期されるエラーの処理 {#handling-expected-errors}

予期されるエラーは、アプリケーションの通常の動作中に発生する可能性があるもので、[サーバーサイドのフォームバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)や失敗したリクエストからのエラーなどが含まれます。これらのエラーは明示的に処理し、クライアントに返すべきです。

### サーバーアクションからの予期されるエラーの処理 {#handling-expected-errors-from-server-actions}

`useFormState`フックを使用してサーバーアクションの状態を管理し、エラーを処理します。このアプローチでは、予期されるエラーに対して`try`/`catch`ブロックを避け、例外を投げるのではなく戻り値としてモデル化します。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

その後、アクションを`useFormState`フックに渡し、返された`state`を使用してエラーメッセージを表示できます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react-dom'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

> **Good to know**: これらの例では、Next.js App RouterにバンドルされているReactの`useFormState`フックを使用しています。React 19を使用している場合は、代わりに`useActionState`を使用してください。詳細については[Reactのドキュメント](https://react.dev/reference/react/useActionState)をご覧ください。

また、返された状態を使用してクライアントコンポーネントからトーストメッセージを表示することもできます。

### サーバーコンポーネントからの予期されるエラーの処理 {#handling-expected-errors-from-server-components}

Server Component内でデータを取得する際、レスポンスを使用してエラーメッセージを条件付きでレンダリングしたり、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)したりすることができます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## キャッチされない例外 {#uncaught-exceptions}

キャッチされない例外は、バグや通常のアプリケーションフローで発生してはならない問題を示す予期しないエラーです。これらはエラーをスローして処理され、その後エラーボーダリーでキャッチされます。

- **一般的な処理**：`error.js`を使って、root レイアウトの下でキャッチされないエラーを処理します
- **任意の処理**：ネストした`error.js`ファイル（例：`app/dashboard/error.js`）を使って詳細なキャッチされないエラーを処理します
- **稀な処理**：`global-error.js`を使ってroot レイアウト内でキャッチされないエラーを処理します

### エラーボーダリーの使用 {#using-error-boundaries}

Next.jsはキャッチされない例外を処理するためにエラーボーダリーを使用します。エラーボーダリーは、その子コンポーネント内のエラーをキャッチし、クラッシュしたコンポーネントツリーの代わりにフォールバックUIを表示します。

エラーボーダリーを作成するには、ルートセグメント内に`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートします：

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // エラーボーダリーはClient Componentsである必要があります

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラー報告サービスに記録します
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何か問題が発生しました！</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて復旧を試みます
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // エラーボーダリーはClient Componentsである必要があります

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラー報告サービスに記録します
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何か問題が発生しました！</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて復旧を試みます
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーを親エラーボーダリーにバブルアップさせたい場合は、`error`コンポーネントをレンダリングする際に`throw`できます。

### ネストされたルートでのエラーの処理 {#handling-errors-in-nested-routes}

エラーは最も近い親エラーボーダリーにバブルアップします。これにより、異なるレベルに`error.tsx`ファイルを配置することで、[ルート階層](/docs/app/building-your-application/routing#component-hierarchy)に詳細なエラー処理を行うことができます。

<Image
  alt="ネストされたエラーコンポーネントの階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

あまり一般的ではありませんが、[国際化](/docs/app/building-your-application/routing/internationalization)を活用している場合でも、root レイアウトを使用してエラーを処理することができます。アクティブな場合、root レイアウトまたはテンプレートを置き換えるため、グローバルエラーUIには独自の`<html>`タグと`<body>`タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // エラーボーダリーはClient Componentsである必要があります

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>何か問題が発生しました！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // エラーボーダリーはClient Componentsである必要があります

export default function GlobalError({ error, reset }) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>何か問題が発生しました！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
